name: plant_disease_detection_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2
  provider: ^6.0.1
  image_picker: ^0.8.5+3
  camera: ^0.10.0+4
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  http_parser: ^4.0.2
  mqtt_client: ^9.6.1
  syncfusion_flutter_gauges: ^20.1.48

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/image/iconApp.png"  # Path to your icon

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/LoginRegisBackground.jfif
    - lib/image/iconApp.png
    - lib/image/apple.jpg
    - lib/image/grape.jpg
    - lib/file.json
